[lightning]
lnd_grpc_host = 'https://lnd:10001'
lnd_cert_file = '/lnd/tls.cert'
lnd_macaroon_file = '/lnd/data/chain/bitcoin/regtest/admin.macaroon'

# lightning invoices sent by the buyer to Mostro should have at least
# this expiration time in seconds
invoice_expiration_window = 3600
# Hold invoice cltv delta (expiration time in blocks)
hold_invoice_cltv_delta = 144
# This is the time that a taker has to pay the invoice (seller) or
# to add a new invoice (buyer), in seconds
hold_invoice_expiration_window = 300
# Retries for failed payments
payment_attempts = 3
# Retries interval for failed payments
payment_retries_interval = 60

[nostr]
# mostro nsec (match devenv MOSTRO_MNEMONIC m/44'/1237'/38383'/0/0)
nsec_privkey = 'nsec1up62kccjww6jg70veks7rt4xa40ggqysdadfm5syyts5u444mfvsjnmf6h'
relays = ['ws://nostr_relay:8080']

[mostro]
# Mostro Fee
fee = 0
# Max routing fee that we want to pay to the network, 0.001 = 0.1%
max_routing_fee = 0.001
# Max order amount (sats)
max_order_amount = 1000000
# Minimum amount for a payment in satoshis
min_payment_amount = 100
# Expiration order hours
expiration_hours = 24
# Max expiration days for an order
max_expiration_days = 15
# Expiration of pending orders
expiration_seconds = 900
# User rate events scheduled time interval
user_rates_sent_interval_seconds = 3600
# Relay list event time interval
publish_relays_interval = 60
# Requested POW
pow = 0
# Publish mostro info interval
publish_mostro_info_interval = 300

[database]
url = "sqlite:///home/mostro/.mostro/mostro.db"
