x-healthcheck: &healthcheck
  interval: 10s
  timeout: 10s
  retries: 10
  start_period: 1m
x-depends-on-bitcoin: &depends_on_bitcoin
  bitcoin:
    condition: service_healthy
    restart: true

services:  
  bitcoin:
    build:
      context: ./docker/bitcoin
    container_name: bitcoin
    restart: unless-stopped
    command: "bitcoind -debug=${MOSTRO_BITCOIN_DEBUG:-0}"
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "bitcoin-cli -regtest -rpcport=18443 -rpcuser=bitcoin -rpcpassword=bitcoin getblockchaininfo"]
    expose:
      - 18443 # RPC
      - 18444 # P2P
      - 29000 # ZMQ TX
      - 29001 # ZMQ BLOCK
      - 29002 # ZMQ HASH BLOCK
    ports:
      - '${MOSTRO_BITCOIN_RPC_LOCAL_PORT:-18443}:18443'
      - '${MOSTRO_BITCOIN_ZMQTX_LOCAL_PORT:-29000}:29000'
      - '${MOSTRO_BITCOIN_ZMQBLOCK_LOCAL_PORT:-29001}:29001'
      - '${MOSTRO_BITCOIN_ZMQHASHBLOCK_LOCAL_PORT:-29002}:29002'
    volumes:
      - bitcoin:/home/bitcoin/.bitcoin

  mostro_lnd:
    build:
      context: ./docker/lnd
    container_name: mostro_lnd
    restart: unless-stopped
    command: 'lnd --alias=mostro_lnd --externalip=mostro_lnd --tlsextradomain=mostro_lnd --tlsextradomain=host.docker.internal'
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "lncli --network=regtest --rpcserver=localhost:10001 --lnddir=/home/lnd/.lnd getinfo"]
    depends_on: *depends_on_bitcoin
    expose:
      - 9735  # P2P
      - 10001 # RPC
      - 8081  # REST
    ports:
      - '${MOSTRO_LND_RPC_LOCAL_PORT:-10001}:10001'
      - '${MOSTRO_LND_REST_LOCAL_PORT:-8081}:8081'
    volumes:
      - mostro_lnd:/home/lnd/.lnd

  nostr_relay:
    build:
      context: ./docker/nostr_relay
    container_name: nostr_relay
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "nak relay nostr_relay:8080"]
    expose:
      - 8080  # WS
    ports:
      - '${MOSTRO_NOSTR_RELAY_LOCAL_PORT:-8080}:8080'
    volumes:
      - nostr_relay:/home/dev/.nostr_relay
  
  mostro:
    build:
      context: ./docker/mostro
    container_name: mostro
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "nak req -k 38383 -a 724497f34e6c4f55f9aa90f5e9dcc326c76a9f2ed817b0f0eb940ee7218ac8d5 ws://nostr_relay:8080 | jq -r '.tags[][0]' | grep mostro_pubkey"]
    depends_on:
      mostro_lnd:
        condition: service_healthy
        restart: true
      nostr_relay:
        condition: service_healthy
        restart: true
    volumes:
      - mostro:/home/mostro/.mostro
      - mostro_lnd:/lnd

volumes:
  bitcoin:
  mostro_lnd:
  nostr_relay:
  mostro:
