x-healthcheck: &healthcheck
  interval: 10s
  timeout: 10s
  retries: 10
  start_period: 1m
x-depends-on-bitcoin: &depends_on_bitcoin
  bitcoin:
    condition: service_healthy
    restart: true

services:  
  bitcoin:
    build:
      context: ./docker/bitcoin
    container_name: bitcoin
    restart: unless-stopped
    command: "bitcoind -debug=${MOSTRO_BITCOIN_DEBUG:-0}"
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "bitcoin-cli -regtest -rpcport=18443 -rpcuser=bitcoin -rpcpassword=bitcoin getblockchaininfo"]
    expose:
      - 18443 # RPC
      - 18444 # P2P
      - 29000 # ZMQ TX
      - 29001 # ZMQ BLOCK
      - 29002 # ZMQ HASH BLOCK
    ports:
      - '${MOSTRO_BITCOIN_RPC_LOCAL_PORT:-18443}:18443'
      - '${MOSTRO_BITCOIN_ZMQTX_LOCAL_PORT:-29000}:29000'
      - '${MOSTRO_BITCOIN_ZMQBLOCK_LOCAL_PORT:-29001}:29001'
      - '${MOSTRO_BITCOIN_ZMQHASHBLOCK_LOCAL_PORT:-29002}:29002'
    volumes:
      - bitcoin:/home/bitcoin/.bitcoin

  lnd:
    hostname: lnd
    depends_on: *depends_on_bitcoin
    image: boltz/lnd:0.18.2-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd:9735 --rpclisten=lnd:10001 --restlisten=lnd:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoin --bitcoind.zmqpubrawtx=bitcoin:29000 --bitcoind.zmqpubrawblock=bitcoin:29001 --bitcoind.rpcuser=bitcoin --bitcoind.rpcpass=bitcoin --noseedbackup --protocol.wumbo-channels'"
    ports:
      - "10001:10001" 
      - "9735:9735"
      - "8081:8081"
    expose:
      - 8081
      - 9735
      - 10001
    volumes:
      - ./data/lnd:/root/.lnd/

  mostro:
    hostname: mostro
    depends_on:
      - lnd
    build:
      #context: ..
      dockerfile: ./mostro/docker/Dockerfile
    volumes:
      - ./mostro/config/:/config  # settings.toml and mostro.db
      - ./mostro/docker/data/lnd:/lnd # LND data
    platform: linux/amd64
  
  nostr_relay:
    build:
      context: ./docker/nostr_relay
    container_name: nostr_relay
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "nak relay nostr_relay:8080"]
    expose:
      - 8080  # WS
    ports:
      - '${MOSTRO_NOSTR_RELAY_LOCAL_PORT:-8080}:8080'
    volumes:
      - nostr_relay:/home/dev/.nostr_relay

volumes:
  bitcoin:
  nostr_relay:
